name: tfma
description: A new Flutter application.



version: 3.0.1+4


environment:
  sdk: '>3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 500